TILE_DIMENSIONS = (50, 50)
DOMINO_DIMENSIONS = (TILE_DIMENSIONS[0] * 2, TILE_DIMENSIONS[1]) ##horizontal by default
PIP_DIAMETER = 10

SCREEN_DIMENSIONS = (10,10)


PLAYER_HAND_LIMIT = 7

HOST = 'localhost'
PORT = 12347
NUM_PLAYERS = 2
CAPACITY = 5
SLEEP_TIME = 1

BOARD_EMPTY = ' '