import math
TILE_DIMENSIONS = (50, 50)
DOMINO_DIMENSIONS = (TILE_DIMENSIONS[0] * 2, TILE_DIMENSIONS[1]) ##horizontal by default
PIP_DIAMETER = 10

SCREEN_DIMENSIONS = (20,10)
DASHBOARD_DIMENSIONS = 200
DASHBOARD_DOMINO_SPACING = 10
DASHBOARD_MAX_DOMINOES_HORIZONTAL = math.floor((SCREEN_DIMENSIONS[0] * TILE_DIMENSIONS[0]-DASHBOARD_DOMINO_SPACING)/(DOMINO_DIMENSIONS[0]+DASHBOARD_DOMINO_SPACING))
DASHBOARD_MAX_DOMINOES_VERTICAL = math.floor((DASHBOARD_DIMENSIONS-DASHBOARD_DOMINO_SPACING)/(DOMINO_DIMENSIONS[1]+DASHBOARD_DOMINO_SPACING))


PLAYER_HAND_LIMIT = 7

HOST = 'localhost'
PORT = 12347
NUM_PLAYERS = 1
CAPACITY = 2
SLEEP_TIME = 1

BOARD_EMPTY = ' '