TILE_DIMENSIONS = (50, 50)
DOMINO_DIMENSIONS = (TILE_DIMENSIONS[0] * 2, TILE_DIMENSIONS[1]) ##horizontal by default
PIP_DIAMETER = 10

SCREEN_DIMENSIONS = (10,10)
DASHBOARD_DIMENSIONS = 100


PLAYER_HAND_LIMIT = 1

HOST = 'localhost'
PORT = 12347
NUM_PLAYERS = 1
CAPACITY = 1
SLEEP_TIME = 1

BOARD_EMPTY = ' '